apiVersion: v1
kind: Service
metadata:
  name: demo-svc
  namespace: beta
spec:
  selector:
    app: demo
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 3000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
  labels:
    app: demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
      namespace: beta
    spec:
      containers:
        - name: demo
          image: nest-cloud-run
          env:
            - name: NODE_ENV
              value: "production"
          ports:
            - containerPort: 3000
          imagePullPolicy: IfNotPresent
      serviceAccountName: default
